// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-dVufue04JflHDp4pngsrB-_M_2z75Y',
    appId: '1:824750606617:web:f216084f0ab3108eaa1d88',
    messagingSenderId: '824750606617',
    projectId: 'voiceforherflutter',
    authDomain: 'voiceforherflutter.firebaseapp.com',
    storageBucket: 'voiceforherflutter.firebasestorage.app',
    measurementId: 'G-08Q0JP9R90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzGtoSaZAc4h4AvPJsqNxJQfsrqQt8UM',
    appId: '1:824750606617:android:14cd4108be14bfa7aa1d88',
    messagingSenderId: '824750606617',
    projectId: 'voiceforherflutter',
    storageBucket: 'voiceforherflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4eTaS5mODPT-grhSwEam1iaWgt1zpgPo',
    appId: '1:824750606617:ios:e8bccf52dabe0d4baa1d88',
    messagingSenderId: '824750606617',
    projectId: 'voiceforherflutter',
    storageBucket: 'voiceforherflutter.firebasestorage.app',
    iosBundleId: 'com.voiceforher.org.voiceforher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4eTaS5mODPT-grhSwEam1iaWgt1zpgPo',
    appId: '1:824750606617:ios:e8bccf52dabe0d4baa1d88',
    messagingSenderId: '824750606617',
    projectId: 'voiceforherflutter',
    storageBucket: 'voiceforherflutter.firebasestorage.app',
    iosBundleId: 'com.voiceforher.org.voiceforher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-dVufue04JflHDp4pngsrB-_M_2z75Y',
    appId: '1:824750606617:web:639255682d6e2ee4aa1d88',
    messagingSenderId: '824750606617',
    projectId: 'voiceforherflutter',
    authDomain: 'voiceforherflutter.firebaseapp.com',
    storageBucket: 'voiceforherflutter.firebasestorage.app',
    measurementId: 'G-M1F2WP753R',
  );
}
